package com.mislbd.ababil.foreignremittance.repository.schema;

public class SchemaConstant {

  static final String NOSTRO_ACCOUNT_TABLE_NAME = "ID_NOSTRO_ACCOUNT";
  static final String NOSTRO_ACCOUNT_SEQUENCE_NAME = "S_ID_NOSTRO_ACCOUNT";

  static final String SHADOW_ACCOUNT_TABLE_NAME = "ID_SHADOW_ACCOUNT";
  static final String SHADOW_ACCOUNT_SEQUENCE_NAME = "S_ID_SHADOW_ACCOUNT";

  static final String ID_PRODUCT_TABLE_NAME = "ID_PRODUCT";
  static final String ID_PRODUCT_SEQUENCE_NAME = "S_ID_PRODUCT";

  static final String SHADOW_ACCOUNT_NUMBER = "SHADOW_ACCOUNT_NUMBER";
  static final String SHADOW_ACCOUNT_NUMBER_SEQUENCE_NAME = "S_SHADOW_ACCOUNT_NUMBER";

  static final String ID_CHARGE_TABLE_NAME = "ID_CHARGE_CONFIGURATION";
  static final String ID_CHARGE_SEQUENCE_NAME = "S_ID_CHARGE_CONFIGURATION";

  static final String ID_CHARGE_SLAB_INFO_TABLE_NAME = "ID_CHARGE_SLAB";
  static final String ID_CHARGE_SLAB_INFO_SEQUENCE_NAME = "S_ID_CHARGE_SLAB";

  static final String ID_REMITTANCE_TRANSACTION_TABLE_NAME = "ID_TRANSACTION";
  static final String ID_REMITTANCE_TRANSACTION_SEQUENCE_NAME = "S_TRANSACTION";

  static final String ID_REMITTANCE_BANK_MAPPING_TABLE_NAME = "ID_REMITTANCE_BANK_MAPPING";
  static final String ID_REMITTANCE_BANK_MAPPING_SEQUENCE_NAME = "S_ID_REMITTANCE_BANK_MAPPING";

  static final String ID_TRANSACTION_TYPE_TABLE_NAME = "ID_TRANSACTION_TYPE";
  static final String ID_TRANSACTION_TYPE_SEQUENCE_NAME = "S_ID_TRANSACTION_TYPE";

  static final String ID_CB_FUND_SOURCE_TABLE_NAME = "ID_CB_FUND_SOURCE";
  static final String ID_CB_FUND_SOURCE_SEQUENCE_NAME = "S_ID_CB_FUND_SOURCE";

  static final String ID_CHARGE_INFO_TABLE_NAME = "ID_CHARGE_INFO";
  static final String ID_CHARGE_INFO_SEQUENCE_NAME = "S_ID_CHARGE_INFO";

  static final String ID_CHARGE_MAPPING_TABLE = "ID_CHARGE_MAPPING";
  static final String ID_CHARGE_MAPPING_SEQUENCE_NAME = "S_ID_CHARGE_MAPPING";

  static final String ID_BANK_TYPE_TABLE_NAME = "ID_BANK_TYPE";
  static final String ID_BANK_TYPE_SEQUENCE_NAME = "S_ID_BANK_TYPE";

  static final String ID_SWIFT_REGISTER = "ID_SWIFT_REGISTER";
  static final String ID_SWIFT_REGISTER_SEQUENCE_NAME = "S_ID_SWIFT_REGISTER";

  static final String ID_SWIFT_BANK_CONFIGURATION_TABLE_NAME = "ID_SWIFT_BANK_MAPPING";
  static final String ID_SWIFT_BANK_CONFIGURATION_SEQUENCE_NAME = "S_ID_SWIFT_BANK_MAPPING";

  static final String SHADOW_TRANSACTION_RECORD_TABLE_NAME = "ID_SHADOW_TXN";
  static final String SHADOW_TRANSACTION_RECORD_SEQUENCE_NAME = "S_ID_SHADOW_TXN_ID";

  static final String NOSTRO_TRANSACTION_RECORD_TABLE_NAME = "ID_NOSTRO_TRANSACTION_RECORD";
  static final String NOSTRO_TRANSACTION_RECORD_SEQUENCE_NAME = "S_ID_NOSTRO_TRANSACTION_RECORD";

  static final String PAYMENT_PURPOSE_TABLE_NAME = "ID_PAYMENT_PURPOSE";

  static final String ID_PRODUCT_CURRENCIES_TABLE_NAME = "ID_PRODUCT_CURRENCIES";

  static final String ID_SENDER_RECEIVER_CUSTOMER_TABLE_NAME = "ID_SENDER_RECEIVER_CUSTOMER";
  static final String ID_SENDER_RECEIVER_CUSTOMER_SEQUENCE_NAME = "S_ID_SENDER_RECEIVER_CUSTOMER";
}
